#!/usr/bin/env bash

set -e 

help()
{
    echo "usage: $0 <options> <project-dir>"
    echo "-w|--work-directory <work-directory>; optional"
}

if [ $# -eq 0 ]; then
    help
    exit
fi

while true; do
    case "$1" in
        -w|--work-directory) workdir="$2"; shift 2;;
        -*) die "unrecognized option: $1";;
        *) break;;
    esac
done

projectdir="$1"

ssh poni  "mkdir '$projectdir' && cd '$projectdir' && git init --bare"

git clone poni:"$projectdir"

cd "$projectdir"

ln -s "$workdir" work

cat - > .gitignore <<END
.Rproj.user
.Rhistory
.RData
work
cache*
figure*
*.html
*.md
*.Rproj
END


git submodule add https://github.com/assaron/r-utils

git add .gitignore
git commit -m "initial commit"
git push --set-upstream origin master
